apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.argotal.com/RuudHermans/home-platform.git
    targetRevision: main
    path: kubernetes/manifests/zot
  destination:
    server: https://kubernetes.default.svc
    namespace: zot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
